name: on-demand-integration-test

on:
  workflow_dispatch:
    
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
      - name: print latest_commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
  build_geff_module:
    runs-on: hpc
    name: Build GEFF Module
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    steps:
      - name: Build GEFF with CMAKE
        uses: ecmwf-actions/reusable-workflows/ci-hpc-generic@v2
        with:
          template: |
            set -eux
            echo "Job is running on ${{ runner.os }}"

            # Load modules of interest
            module load ecmwf-toolbox
            module load cmake

            # Clone the repository
            PACKAGE_NAME=geff
            PACKAGE_BRANCH=${{ github.head_ref || github.ref_name }}
            git clone -b $PACKAGE_BRANCH https://${{ secrets.GH_REPO_READ_TOKEN }}@github.com/ecmwf/${PACKAGE_NAME}.git
            cd $PACKAGE_NAME
            mkdir build && cd build
            cmake ../
            make

          sbatch_options: |
            #SBATCH --job-name=geff_build
            #SBATCH --time=00:10:00
            #SBATCH --qos=nf
          troika_user: ${{ secrets.HPC_CI_INTEGRATION_USER }}
          site: hpc-batch
